# This file is a template, and might need editing before it works on your project.
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Python.gitlab-ci.yml

# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/python/tags/
image: python:3.11

stages:
  - test_syntax
  - bandit

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

# Pip's cache doesn't store the python packages
# https://pip.pypa.io/en/stable/topics/caching/
# Используемое кеширование на основе ключей, одначает, что будет происходить проверка
# неизменности заданных файлов-ключей, и если они не были изменены, то директории в paths
# будут взяты из кэша (например если если poetry.lock остался прежним, то не нужно 
# переустанавливать заново всю виртуальную среду)
cache:
  key:
    files:
      - poetry.lock
  paths:
    - .venv/

before_script:
  - python --version  # For debugging
  - python -m pip install poetry
  - poetry config virtualenvs.in-project true
  - poetry install

flake8:
 stage: test_syntax
 script:
   - poetry run flake8 src

ruff:
 stage: test_syntax
 script:
   - poetry run ruff check src

bandit:
  stage: bandit
  script:
    - poetry run bandit -c pyproject.toml -r src